### ISSUE TITLE
jQuery dosent work 

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1016]
some of my  jQuery dosent work in newest  PHP F Version. 
on older versions it was working correct all times

Popup image upload --> no work
Date Picker --> no work

live here: http://aliencollectors.com/site/infusions/figurelib/submit.php?stype=f
code is here:  https://github.com/Catzenjaeger/FigureLib_4/blob/master/infusions/figurelib/submit.php

its definitively a PHP F9 problem well in older versions from the last days it have work to 100%. 

here on video upload it works but not on image upload
![ashampoo_snap_2016 09 03_13h52m56s_020_](https://cloud.githubusercontent.com/assets/19621858/18224657/9d35576c-71dd-11e6-8947-44b6597997a0.jpg)

same popup comes normally on image upload

**Comment by RobiNN1** [comment]
Fixed

**Comment by Catzenjaeger** [comment]
file???

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/467b01fae2a86dde4c1bd10a81103906929b8297

**Comment by Catzenjaeger** [comment]
hmnn i have change the files but it dosent work :(

**Comment by Catzenjaeger** [comment]
it not solved - look on my site with fresh installed php fusion (15:00 german time)
the 4 changes for bootstrap problem i have replaced

send me a email and i give you a testlogin as admin for this site so you can watch

**Comment by meangczac** [comment]
This one solved.
